<CENTER style="font-size:40px;">Experiment 5</CENTER>

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;width:100%}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  overflow:hidden;padding:10px 10px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  font-weight:normal;overflow:hidden;padding:10px 10px;word-break:normal;}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top;}
.col1 { width: 20%;}
.col2 { width: 80%;}
</style>
<table style="width: 100%;">
  <tr>
    <td>Name</td>
    <td>Pranay Singhvi</td>
  </tr>
  <tr>
    <td>UID</td>
    <td>2021300126</td>
  </tr>
</table>

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;width:100%}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  overflow:hidden;padding:10px 10px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:16px;
  font-weight:normal;overflow:hidden;padding:10px 10px;word-break:normal;}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top;}
.col1 { width: 20%;}
.col2 { width: 80%;}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-0pky col1">HONOR PLEDGE</th>
    <th class="tg-0pky col2">
        <img src="../1_/Honour.jpeg" alt="honor pledge">
    </th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-0pky col1">PROBLEM STATEMENT</td>
    <td class="tg-0pky col2" style="font-size:16px;">
      <strong>Data Quality Assurance :</strong>
      Answer the following question first:
      <br>
What are the 6 core dimensions of data quality? Elaborate on each with an example. Is there any other dimension that you can think of apart from these 6 for measuring quality?
<br>
● Pick a time-series dataset from either of these websites based on batch majority:
1) https://data.gov.in
2) https://data.oecd.org
3) Kaggle
<br>
● Assess the quality of this dataset on all the dimensions of quality as identified by you.
<br>
● Identify and handle inconsistent or erroneous data
<br>
● Calculate data quality metrics for each data quality dimension for your dataset
    </td>
  </tr>
  <tr>
    <td class="tg-0pky col1">THEORY</td>
    <td class="tg-0pky col2">
    <strong>Resampling Time Series</strong>
<ul>
  <li><b>Purpose</b>: Resampling changes the granularity of a time series. You might resample to analyze trends at a lower level (e.g., hourly data to daily trends) or aggregate to a higher level (e.g., daily to monthly performance).</li>
  <li><b>Upsampling</b>: Increasing the frequency of data (e.g., daily to hourly). Techniques include:
    <ul>
    <li> <b>Forward Fill (FFill)</b>: Propagates the last valid observation forward to fill in missing values. Useful when changes between points are expected to be minimal.</li>
    <li><b>Interpolation</b>: Estimates missing values using existing data points (e.g., linear interpolation). This is more complex but generally smoother than FFill.</li>
    </ul>
  </li>
  <li><b>Downsampling</b>: Decreasing the frequency of data (e.g., hourly to daily). Techniques include:
    <ul>
    <li> <b>Aggregation</b>: Calculate summary statistics (average, sum, max, min) within each new time window.</li>
    <li><b>OHLC Sampling</b>: Preserves Open, High, Low, and Close values of a times series. This is mainly used in financial data analysis.</li>
    </ul>
  </li>
</ul>







<strong>Shifting Time Series</strong>
<ul>
<li><b>Purpose</b>: Shifting is crucial for creating lagged features. Lagged features allow you to incorporate historical trends into forecasting and models.</li>
<li><b>Naive Shift</b>: Simple shifting by a defined number of periods. For example, shifting by one period in a daily time series aligns today's data point with yesterday's.</li>
<li><b>Shifting Using Frequency</b>: Leverages the underlying frequency of your time series for more precise shifts. You might shift data forward by two months if working with monthly data.</li>
</ul>
<strong>Moving Averages and Rolling Sums</strong>
<ul>
<li><b>Purpose</b>: Smoothing time series to reduce noise and reveal underlying trends. These techniques give you insights into trend direction and momentum.</li>
<li><b>Moving Averages (MA)</b>:</li>
<ul>
<li><b>Simple Moving Average (SMA)</b>: Averages a fixed number of past data points, giving them equal weight. As time progresses, the calculation window 'moves' through the data.</li>
<li><b>Weighted Moving Average (WMA)</b>: Allows for greater weighting of more recent data points, which emphasizes current trends.</li>
<li><b>Exponential Moving Average (EMA)</b>: Applies exponential weighting that decreases over time. This allows EMAs to react more quickly to recent changes in the data.</li>
</ul>
<li><b>Rolling Sums</b>: Calculated over a specified window, providing the cumulative sum of values within that window. For example, a 30-day rolling sum displays the total over the past 30 days.</li>
</ul>
    </td>
  </tr>
</tbody>
</table>

### 1.Import Library

In [30]:
import pandas as pd
from datetime import datetime
import numpy as np

In [31]:
df = pd.read_csv('Flight_Schedule.csv')

/var/folders/fc/b_3ntmtx3kv_43ckpdzjd47r0000gn/T/ipykernel_75052/3349952028.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Flight_Schedule.csv')

In [32]:
df

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated
0,GoAir,425,Delhi,Hyderabad,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",05:45,NaN,2019-03-30,2018-10-28,2019-03-30,2023-11-05
1,GoAir,423,Delhi,Hyderabad,Saturday,07:30,NaN,2018-10-28,2018-10-28,2018-10-28,2023-11-05
2,GoAir,423,Delhi,Hyderabad,Friday,07:30,NaN,2018-12-01,2018-11-03,2018-12-01,2023-11-05
3,GoAir,423,Delhi,Hyderabad,Friday,07:30,NaN,2019-03-30,2019-02-02,2019-03-30,2023-11-05
4,GoAir,423,Delhi,Hyderabad,"Sunday,Monday,Tuesday,Wednesday,Thursday,Saturday",07:30,NaN,2018-11-30,2018-10-29,2018-11-30,2023-11-05
...,...,...,...,...,...,...,...,...,...,...,...
88977,SpiceJet,2923,Hyderabad,Shirdi Airport,"Sunday,Tuesday,Thursday,Saturday",NaN,16:35,2023-10-28,2023-03-26,2023-10-28,2023-11-05
88978,SpiceJet,2923,Tirupati,Shirdi Airport,"Monday,Wednesday,Friday",NaN,16:50,2023-10-28,2023-03-26,2023-10-28,2023-11-05
88979,SpiceJet,0329,Chennai,Shirdi Airport,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,16:20,2023-10-28,2023-03-26,2023-10-28,2023-11-05
88980,SpiceJet,2950,Delhi,Kangra,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,07:30,2023-10-28,2023-03-26,2023-10-28,2023-11-05
88981,SpiceJet,2345,Delhi,Kangra,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,10:00,2023-10-28,2023-03-26,2023-10-28,2023-11-05

In [33]:
df.isnull().sum()

airline                     675
flightNumber                323
origin                      500
destination                 547
daysOfWeek                    1
scheduledDepartureTime    30686
scheduledArrivalTime      30968
timezone                      0
validFrom                     0
validTo                       0
lastUpdated                   0
dtype: int64

In [34]:
def check_accuracy(df):
    # Check if categorical columns have accurate and valid values
    valid_airlines = ['GoAir', 'Air India', 'AirAsia India', 'Jet Airways','Alliance Air (India)', 'Jetlite', 'Vistara', 'IndiGo', 'TruJet', 'SpiceJet', 'FlyBig', 'Star Air', 'Akasa Air', 'IndiaOne Air']# Add valid airline names if needed
    valid_origins = ['Delhi', 'Lucknow', 'Kochi', 'Ahmedabad', 'Jaipur', 'Bengaluru',
       'Guwahati', 'Goa', 'Kolkata', 'Hyderabad', 'Nagpur', 'Bagdogra',
       'MIHAN', 'Mumbai', 'Leh', 'Patna', 'Ranchi', 'Pune', 'Jammu',
       'Srinagar', 'Chennai', 'Bhubaneswar', 'Port Blair', 'Chandigarh',
       'Visakhapatnam', 'Vijayawada', 'Tirupati', 'Varanasi',
       'Aurangabad', 'Rajkot', 'Amritsar', 'Imphal', 'Jodhpur', 'Indore',
       'Vadodara', 'Raipur', 'Udaipur', 'Surat', 'Bhopal', 'Gaya',
       'Khajuraho', 'Thiruvananthapuram', 'Mangalore', 'Calicut', 'Hubli',
       'Coimbatore', 'Jamnagar', 'Nanded', 'Aizwal', 'Dibrugarh',
       'Madurai', 'Agra', 'Dimapur', 'Silchar', 'Agartala', 'Nasik',
       'Dehradun', 'Allahabad', 'Jorhat', 'Tiruchirappalli',
       'Kolhapur', 'Shirdi Airport', 'Kullu', 'Gorakhpur', 'Ludhiana',
       'Shimla', 'Gwalior', 'Pantnagar', 'Bikaner', 'Bathinda',
       'Jabalpur', 'Pathankot', 'Kangra', 'Agatti', 'Diu', 'Bhavnagar',
       'Kandla', 'Belgaum', 'Lilabari', 'Tezpur', 'Passighat', 'Shillong',
       'Rajahmundry', 'Tuticorin', 'Vidyanagar', 'Jalgaon', 'Keshod',
       'Porbandar', 'Salem', 'Mysore', 'Pondicherry', 'Adampur',
       'Jaisalmer', 'Kanpur', 'Kishangarh', 'Pakyong', 'Tezu',
       'Kannur International Airport', 'Bhuj', 'Kadapa', 'Jharsuguda',
       'Pithoragarh', 'Kalaburgi (Gulbarga)', 'Bidar', 'Thoise', 'Rupsi',
       'Durgapur', 'Darbhanga', 'Bilaspur', 'Mundra', 'Hindon Airport',
       'Cooch-Behar']  # Add valid origin locations if needed
    valid_destinations = ['Hyderabad', 'Delhi', 'Varanasi', 'Bhubaneswar', 'Nagpur',
       'Bagdogra', 'MIHAN', 'Lucknow', 'Kochi', 'Mumbai', 'Leh', 'Patna',
       'Port Blair', 'Kannur International Airport', 'Ahmedabad',
       'Jaipur', 'Bengaluru', 'Ranchi', 'Chandigarh', 'Pune', 'Guwahati',
       'Chennai', 'Jammu', 'Goa', 'Kolkata', 'Srinagar',
       'Thiruvananthapuram', 'Mangalore', 'Calicut', 'Aurangabad',
       'Madurai', 'Rajkot', 'Gaya', 'Dimapur', 'Visakhapatnam',
       'Amritsar', 'Imphal', 'Agra', 'Jodhpur', 'Vijayawada', 'Indore',
       'Vadodara', 'Silchar', 'Raipur', 'Udaipur', 'Tirupati', 'Belgaum',
       'Hubli', 'Aizwal', 'Surat', 'Coimbatore', 'Khajuraho', 'Bhopal',
       'Dibrugarh', 'Agartala', 'Nanded', 'Jamnagar', 'Nasik',
       'Dehradun', 'Bhuj', 'Allahabad', 'Jorhat', 'Tiruchirappalli',
       'Thoise', 'Shirdi Airport', 'Kandla', 'Kullu', 'Passighat',
       'Shillong', 'Kolhapur', 'Rajahmundry', 'Diu', 'Gorakhpur',
       'Ludhiana', 'Shimla', 'Gwalior', 'Pantnagar', 'Agatti', 'Lilabari',
       'Tezpur', 'Bikaner', 'Bathinda', 'Jabalpur', 'Pathankot',
       'Bhavnagar', 'Kangra', 'Tuticorin', 'Kadapa', 'Salem', 'Jaisalmer',
       'Vidyanagar', 'Adampur', 'Pondicherry', 'Kanpur', 'Kishangarh',
       'Pakyong', 'Jalgaon', 'Mundra', 'Tezu', 'Jharsuguda', 'Mysore',
       'Darbhanga', 'Pithoragarh', 'Kalaburgi (Gulbarga)', 'Keshod',
       'Bidar', 'Hindon Airport', 'Rupsi', 'Bilaspur', 'Cooch-Behar',
       'Porbandar', 'Durgapur']  # Add valid destination locations if needed

    accuracy_checks = (
        df['airline'].isin(valid_airlines) &
        df['origin'].isin(valid_origins) &
        df['destination'].isin(valid_destinations)
    )

    return accuracy_checks

In [35]:
df["destination"].unique()

array(['Hyderabad', 'Delhi', 'Varanasi', 'Bhubaneswar', 'Nagpur',
       'Bagdogra', 'MIHAN', 'Lucknow', 'Kochi', 'Mumbai', 'Leh', 'Patna',
       'Port Blair', 'Kannur International Airport', 'Ahmedabad',
       'Jaipur', 'Bengaluru', 'Ranchi', 'Chandigarh', 'Pune', 'Guwahati',
       'Chennai', 'Jammu', 'Goa', 'Kolkata', 'Srinagar',
       'Thiruvananthapuram', 'Mangalore', 'Calicut', 'Aurangabad',
       'Madurai', 'Rajkot', 'Gaya', 'Dimapur', 'Visakhapatnam',
       'Amritsar', 'Imphal', 'Agra', 'Jodhpur', 'Vijayawada', 'Indore',
       'Vadodara', 'Silchar', 'Raipur', 'Udaipur', 'Tirupati', 'Belgaum',
       'Hubli', 'Aizwal', 'Surat', 'Coimbatore', 'Khajuraho', 'Bhopal',
       'Dibrugarh', 'Agartala', 'Nanded', 'Jamnagar', nan, 'Nasik',
       'Dehradun', 'Bhuj', 'Allahabad', 'Jorhat', 'Tiruchirappalli',
       'Thoise', 'Shirdi Airport', 'Kandla', 'Kullu', 'Passighat',
       'Shillong', 'Kolhapur', 'Rajahmundry', 'Diu', 'Gorakhpur',
       'Ludhiana', 'Shimla', 'Gwalior', 'Pantnagar', 'Agatti', 'Lilabari',
       'Tezpur', 'Bikaner', 'Bathinda', 'Jabalpur', 'Pathankot',
       'Bhavnagar', 'Kangra', 'Tuticorin', 'Kadapa', 'Salem', 'Jaisalmer',
       'Vidyanagar', 'Adampur', 'Pondicherry', 'Kanpur', 'Kishangarh',
       'Pakyong', 'Jalgaon', 'Mundra', 'Tezu', 'Jharsuguda', 'Mysore',
       'Darbhanga', 'Pithoragarh', 'Kalaburgi (Gulbarga)', 'Keshod',
       'Bidar', 'Hindon Airport', 'Rupsi', 'Bilaspur', 'Cooch-Behar',
       'Porbandar', 'Durgapur'], dtype=object)

In [36]:
# Calculate accuracy percentage
df['accuracy'] = check_accuracy(df)
accuracy_percentage = (df['accuracy'].sum() / len(df)) * 100
print(f"Accuracy Percentage: {accuracy_percentage:.2f}%")

Accuracy Percentage: 98.10%

In [37]:
def check_completeness(df):
    # Check for missing values in essential columns
    completeness_checks = ~df[['flightNumber', 'origin', 'destination', 'daysOfWeek',
                               'scheduledDepartureTime', 'scheduledArrivalTime',
                               'timezone', 'validFrom', 'validTo', 'lastUpdated']].isnull().any(axis=1)
    return completeness_checks
df['completeness'] = check_completeness(df)

In [38]:
completeness_percentage = (df['completeness'].sum() / len(df)) * 100

In [39]:
def check_consistency(df):
    # Check consistency in the timezone column
    consistency_checks = pd.to_datetime(df['timezone'], errors='coerce').notna()

    # Check consistency in the daysOfWeek column
    days_of_week_validity = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
    consistency_checks &= df['daysOfWeek'].apply(lambda x: all(day.lower() in days_of_week_validity for day in str(x).split(',')))

    return consistency_checks

In [40]:
df['consistency'] = check_consistency(df)

In [41]:
consistency_percentage = (df['consistency'].sum() / len(df)) * 100
print(f"Consistency Percentage: {consistency_percentage:.2f}%")

Consistency Percentage: 100.00%

In [42]:
def check_timeliness(df):
    # Check if validFrom and validTo dates are within a reasonable time frame
    timeliness_checks = (
        (pd.to_datetime(df['validFrom'], errors='coerce') <= pd.to_datetime(df['validTo'], errors='coerce')) &
        (pd.to_datetime(df['validTo'], errors='coerce') <= datetime.now())
    )

    # Check if lastUpdated date is recent
    timeliness_checks &= (pd.to_datetime(df['lastUpdated'], errors='coerce') <= datetime.now())

    return timeliness_checks

In [43]:
df['timeliness'] = check_timeliness(df)

In [44]:
Timeliness_percentage = (df['timeliness'].sum() / len(df)) * 100
print(Timeliness_percentage)

99.99887617720438

In [45]:
def check_validity(df):
    # Check validity of scheduledDepartureTime and scheduledArrivalTime
    time_format = '%H:%M'
    validity_checks = (
        pd.to_datetime(df['scheduledDepartureTime'], format=time_format, errors='coerce').notna() &
        pd.to_datetime(df['scheduledArrivalTime'], format=time_format, errors='coerce').notna()
    )

    # Check validity of daysOfWeek
    days_of_week_validity = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']
    validity_checks &= df['daysOfWeek'].apply(lambda x: all(day.lower() in days_of_week_validity for day in str(x).split(',')))

    return validity_checks

In [46]:
df['validity'] = check_validity(df)
Validity_percentage = (df['validity'].sum() / len(df)) * 100

In [47]:
def check_reliability(df):
    # Check reliability by examining consistency of data for the same flight
    reliability_checks = df.duplicated(subset=['flightNumber', 'origin', 'destination'], keep=False)

    # Calculate the percentage of reliability
    reliability_percentage = (reliability_checks.sum() / len(df)) * 100

    return reliability_percentage

# Assuming df is your DataFrame
reliability_percentage = check_reliability(df)
print(f"Reliability Percentage: {reliability_percentage:.2f}%")

Reliability Percentage: 91.89%

In [48]:
print(f"Reliability Percentage: {reliability_percentage:.2f}%")
print(f"Consistency Percentage: {consistency_percentage:.2f}%")
print(f"Accuracy Percentage: {accuracy_percentage:.2f}%")
print(f"Timeliness Percentage: {Timeliness_percentage:.2f}%")
print(f"Completness Percentage: {completeness_percentage:.2f}%")
print(f"Validity Percentage: {Validity_percentage:.2f}%")

Reliability Percentage: 91.89%
Consistency Percentage: 100.00%
Accuracy Percentage: 98.10%
Timeliness Percentage: 100.00%
Completness Percentage: 30.57%
Validity Percentage: 30.71%

In [49]:
departure_time_outliers = df[(df['scheduledDepartureTime'] < '00:00:00') | (df['scheduledDepartureTime'] > '23:59:59')]
arrival_time_outliers = df[(df['scheduledArrivalTime'] < '00:00:00') | (df['scheduledArrivalTime'] > '23:59:59')]

In [51]:
arrival_time_outliers

,airline,flightNumber,origin,destination,daysOfWeek,scheduledDepartureTime,scheduledArrivalTime,timezone,validFrom,validTo,lastUpdated,accuracy,completeness,consistency,timeliness,validity
5230,SpiceJet,8482,Surat,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",20:55,00:00,2019-03-30,2018-10-28,2019-03-30,2023-11-05,True,True,True,True,True
5323,SpiceJet,638,Ahmedabad,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",22:45,00:00,2019-03-30,2018-10-28,2019-03-30,2023-11-05,True,True,True,True,True
5325,SpiceJet,638,Ahmedabad,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",23:00,00:00,2019-10-26,2019-03-31,2019-10-26,2023-11-05,True,True,True,True,True
10989,SpiceJet,638,Ahmedabad,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",23:00,00:00,2020-03-28,2019-10-27,2020-03-28,2023-11-05,True,True,True,True,True
16787,SpiceJet,638,Ahmedabad,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",22:45,00:00,2020-10-24,2020-03-29,2020-10-24,2023-11-05,True,True,True,True,True
18117,Air India,480,Amritsar,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",22:45,00:00,2021-03-27,2020-10-25,2021-03-27,2023-11-05,True,True,True,True,True
51977,IndiGo,116,Bengaluru,Pune,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",22:30,00:00,2023-03-25,2022-10-30,2023-03-25,2023-11-05,True,True,True,True,True
53528,GoAir,804,Ahmedabad,Bengaluru,Monday,NaN,00:00,2019-03-26,2018-10-30,2019-03-26,2023-11-05,True,False,True,True,False
53529,GoAir,804,Ahmedabad,Bengaluru,"Sunday,Tuesday,Wednesday,Thursday,Friday,Saturday",NaN,00:00,2019-03-30,2018-10-29,2019-03-30,2023-11-05,True,False,True,True,False
59738,GoAir,138,Chandigarh,Delhi,Saturday,NaN,00:00,2020-10-18,2020-04-05,2020-10-18,2023-11-05,True,False,True,True,False
59739,GoAir,138,Chandigarh,Delhi,"Monday,Tuesday,Wednesday,Thursday,Friday",NaN,00:00,2020-10-24,2020-03-31,2020-10-24,2023-11-05,True,False,True,True,False
62218,Vistara,774,Kolkata,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2020-03-27,2019-10-27,2020-03-27,2023-11-05,True,False,True,True,False
62219,Vistara,774,Kolkata,Mumbai,Friday,NaN,00:00,2020-03-28,2020-03-28,2020-03-28,2023-11-05,True,False,True,True,False
65339,SpiceJet,8710,Mumbai,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2020-06-30,2020-03-29,2020-06-30,2023-11-05,True,False,True,True,False
65402,SpiceJet,8145,Goa,Delhi,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2019-05-31,2019-03-31,2019-05-31,2023-11-05,True,False,True,True,False
66361,GoAir,2608,Jaipur,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2020-10-24,2020-03-30,2020-10-24,2023-11-05,True,False,True,True,False
68085,Vistara,774,Kolkata,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2020-10-23,2020-03-29,2020-10-23,2023-11-05,True,False,True,True,False
76379,IndiGo,276,Delhi,Thiruvananthapuram,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2022-01-15,2022-01-01,2022-01-15,2023-11-05,True,False,True,True,False
76380,IndiGo,276,Delhi,Thiruvananthapuram,Friday,NaN,00:00,2022-03-26,2022-03-26,2022-03-26,2023-11-05,True,False,True,True,False
83560,IndiGo,2114,Delhi,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2023-03-25,2022-10-31,2023-03-25,2023-11-05,True,False,True,True,False
83593,IndiGo,2245,Lucknow,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2023-03-25,2022-10-31,2023-03-25,2023-11-05,True,False,True,True,False
83623,IndiGo,6734,Patna,Mumbai,"Sunday,Monday,Tuesday,Wednesday,Thursday,Frida...",NaN,00:00,2023-03-25,2022-10-31,2023-03-25,2023-11-05,True,False,True,True,False